spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  profiles:
    active: local
  config:
    import: configserver:http://localhost:8001
  main:
    allow-bean-definition-overriding: true
    web-application-type: REACTIVE
